# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Patchflow < Formula
  desc "Local-first security scanner for code, dependencies, and secrets"
  homepage "https://patchflow.dev"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Patchflow-security/patchflow-cli/releases/download/v0.1.1/patchflow_0.1.1_macos_x86_64.tar.gz"
      sha256 "0a3d2a0df40e6bd835eaea0b3a8fe503e6058ea74c68900baecb3e5a4c4efec5"

      define_method(:install) do
        bin.install "patchflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Patchflow-security/patchflow-cli/releases/download/v0.1.1/patchflow_0.1.1_macos_arm64.tar.gz"
      sha256 "8b1a14900a4d1120eb789fe68e7e507e2a199e5897e74ecbd0001662487ee48a"

      define_method(:install) do
        bin.install "patchflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Patchflow-security/patchflow-cli/releases/download/v0.1.1/patchflow_0.1.1_linux_x86_64.tar.gz"
      sha256 "ceac72e6a5a630b35121161dc3bc2e907b7b71dbacc28b0997bf341bf8140954"
      define_method(:install) do
        bin.install "patchflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Patchflow-security/patchflow-cli/releases/download/v0.1.1/patchflow_0.1.1_linux_arm64.tar.gz"
      sha256 "17138ac11c21c1303f3bc98a7503b1c08f148af11329f24227dcfbf86734dc2c"
      define_method(:install) do
        bin.install "patchflow"
      end
    end
  end

  test do
    system "#{bin}/patchflow", "version"
  end
end
