# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Patchflow < Formula
  desc "Local-first security scanner for code, dependencies, and secrets"
  homepage "https://patchflow.dev"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Patchflow-security/patchflow-cli/releases/download/v0.1.3/patchflow_0.1.3_macos_x86_64.tar.gz"
      sha256 "8664a94afdcbeff3483a9d082ee5a3f3cb6fb70cb478cd19350b5cd0d771d479"

      define_method(:install) do
        bin.install "patchflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Patchflow-security/patchflow-cli/releases/download/v0.1.3/patchflow_0.1.3_macos_arm64.tar.gz"
      sha256 "9e016b583b5529fd83c6315f2d2f0edcfc6d972f5c7aecf754f8b0ff17d2b4c0"

      define_method(:install) do
        bin.install "patchflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Patchflow-security/patchflow-cli/releases/download/v0.1.3/patchflow_0.1.3_linux_x86_64.tar.gz"
      sha256 "5d16572145428c4d3bac433a88670800969ce9386738daff542bfb673c29fe4e"
      define_method(:install) do
        bin.install "patchflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Patchflow-security/patchflow-cli/releases/download/v0.1.3/patchflow_0.1.3_linux_arm64.tar.gz"
      sha256 "7c6bd2edaedb83561d867c8d96d2994482ed0b33abba2d2a7da090db836a60e9"
      define_method(:install) do
        bin.install "patchflow"
      end
    end
  end

  test do
    system "#{bin}/patchflow", "version"
  end
end
