# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Patchflow < Formula
  desc "Local-first security scanner for code, dependencies, and secrets"
  homepage "https://patchflow.dev"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Patchflow-security/patchflow-cli/releases/download/v0.1.0/patchflow_0.1.0_macos_x86_64.tar.gz"
      sha256 "0a557f369c45039b1de8c3ed8fa27d67f405ed5078940f824d37d6f49df42382"

      define_method(:install) do
        bin.install "patchflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Patchflow-security/patchflow-cli/releases/download/v0.1.0/patchflow_0.1.0_macos_arm64.tar.gz"
      sha256 "7db50300227c0f0bede71d86b07b0ab9e60820871d4dea557b38d97aea556f74"

      define_method(:install) do
        bin.install "patchflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Patchflow-security/patchflow-cli/releases/download/v0.1.0/patchflow_0.1.0_linux_x86_64.tar.gz"
      sha256 "189923c91b66bcceabc8e07ccbe50a6cea566033e0b2560ddc44c73cebc67004"
      define_method(:install) do
        bin.install "patchflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Patchflow-security/patchflow-cli/releases/download/v0.1.0/patchflow_0.1.0_linux_arm64.tar.gz"
      sha256 "7d83de01aa25237f1c402bad6948af0c6bd180f8586d3ffb23a84b52847ee8a4"
      define_method(:install) do
        bin.install "patchflow"
      end
    end
  end

  test do
    system "#{bin}/patchflow", "version"
  end
end
